services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
  db:
    image: "mongo:7.0"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DB_DATABASE}"
    ports:
      - "${DB_PORT}:27017"
    networks:
      - lavinium
networks:
  lavinium:
    driver: bridge
